# Fichier de routage principal
# Chaque bundle a son propre fichier de routage

app:
    resource: '@AppBundle/Resources/config/routing.yml'

web_service:
    resource: "@WebServiceBundle/Resources/config/routing.yml"
    prefix:   /api

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /
