web_service_homepage:
    path: /
    defaults: { _controller: WebServiceBundle:Default:index }

web_service_get_trajet:
    path: /trajet/{id}/info
    defaults: { _controller: WebServiceBundle:Trajet:getTrajet }
    methods: GET
    requirements:
        id: '\d+'

web_service_get_trajets:
    path: /trajets
    defaults: { _controller: WebServiceBundle:Trajet:getTrajets }
    methods: GET

web_service_get_trajets_utilisateur:
    path: /utilisateur/{id}/trajets
    defaults: { _controller: WebServiceBundle:Covoiturage:getTrajetsUtilisateur }
    methods: GET
    requirements:
        id: '\d+'

web_service_register_to_a_trajet:
    path: /trajet/{id_trajet}/utilisateur/{id_user}
    defaults: { _controller: WebServiceBundle:Covoiturage:registerToATrajet }
    methods: POST
    requirements:
        id_user: '\d+'
        id_trajet: '\d+'

web_service_get_utilisateur:
    path: /utilisateur/{id}/info
    defaults: { _controller: WebServiceBundle:Utilisateur:getUtilisateur }
    methods: GET
    requirements:
        id: '\d+'
