# --- DEBUG ---
web_service_debug:
    path: /
    defaults: { _controller: WebServiceBundle:Default:debug }

# --- TRAJETS ---
web_service_get_trajet:
    path: /trajets/{id}
    defaults: { _controller: WebServiceBundle:Trajet:getTrajet }
    methods: GET
    requirements:
        id: '\d+'

web_service_get_trajets:
    path: /trajets
    defaults: { _controller: WebServiceBundle:Trajet:getTrajets }
    methods: GET

web_service_new_trajet:
    path: /trajets/new
    defaults: { _controller: WebServiceBundle:Trajet:newTrajet }
    methods: POST

web_service_edit_trajet:
    path: /trajets/{id}
    defaults: { _controller: WebServiceBundle:Trajet:editTrajet }
    methods: POST
    requirements:
        id: '\d+'

web_service_delete_trajet:
    path: /trajets/{id}
    defaults: { _controller: WebServiceBundle:Trajet:deleteTrajet }
    methods: DELETE
    requirements:
        id: '\d+'

# ---------------

web_service_get_trajets_utilisateur:
    path: /utilisateur/{id}/trajets
    defaults: { _controller: WebServiceBundle:Covoiturage:getTrajetsUtilisateur }
    methods: GET
    requirements:
        id: '\d+'

web_service_register_to_a_trajet:
    path: /trajet/{id_trajet}/utilisateur/{id_user}
    defaults: { _controller: WebServiceBundle:Covoiturage:registerToATrajet }
    methods: POST
    requirements:
        id_user: '\d+'
        id_trajet: '\d+'

web_service_get_utilisateur:
    path: /utilisateur/{id}/info
    defaults: { _controller: WebServiceBundle:Utilisateur:getUtilisateur }
    methods: GET
    requirements:
        id: '\d+'

web_service_create_utilisateur:
    path: /utilisateur/create
    defaults: { _controller: WebServiceBundle:Utilisateur:createUtilisateur }
    methods: POST

web_service_modify_utilisateur:
    path: /utilisateur/{id}/modify
    defaults: { _controller: WebServiceBundle:Utilisateur:modifyUtilisateur }
    methods: PUT
    requirements:
        id: '\d+'

web_service_delete_utilisateur:
    path: /utilisateur/{id}/delete
    defaults: { _controller: WebServiceBundle:Utilisateur:deleteUtilisateur }
    methods: DELETE
    requirements:
        id: '\d+'

web_service_get_possede:
    path: /possede/{id}
    defaults: { _controller: WebServiceBundle:Possede:getPossede }
    methods: GET
    requirements:
        id: '\d+'

web_service_create_possede:
    path: /possede/create
    defaults: { _controller: WebServiceBundle:Possede:createPossede }
    methods: POST

web_service_modify_possede:
    path: /possede/{id}/modify
    defaults: { _controller: WebServiceBundle:Possede:modifyPossede }
    methods: PUT
    requirements:
        id: '\d+'

web_service_delete_possede:
    path: /possede/{id}/delete
    defaults: { _controller: WebServiceBundle:Possede:deletePossede }
    methods: DELETE
    requirements:
        id_user: '\d+'
        id_voiture: '\d+'

web_service_get_voitures:
    path: /voitures
    defaults: { _controller: WebServiceBundle:Voiture:getVoitures }
    methods: GET

web_service_get_villes:
    path: /villes
    defaults: { _controller: WebServiceBundle:Ville:getVilles }
    methods: GET

web_service_get_categories:
    path: /categories
    defaults: { _controller: WebServiceBundle:Categorie:getCategories }
    methods: GET

web_service_get_type_trajet:
    path: /typestrajet
    defaults: { _controller: WebServiceBundle:TypeTrajet:getTypesTrajet }
    methods: GET

web_service_get_type_covoit:
    path: /typescovoit
    defaults: { _controller: WebServiceBundle:TypeCovoit:getTypesCovoit }
    methods: GET