web_service_categorie:
    resource: "@WebServiceBundle/Resources/config/routing/categorie.yml"
    prefix:   /categories

web_service_covoiturage:
    resource: "@WebServiceBundle/Resources/config/routing/covoiturage.yml"
    prefix:   /covoiturages

web_service_marque:
    resource: "@WebServiceBundle/Resources/config/routing/marque.yml"
    prefix:   /marques

web_service_possede:
    resource: "@WebServiceBundle/Resources/config/routing/possede.yml"
    prefix:   /possedes

web_service_trajet:
    resource: "@WebServiceBundle/Resources/config/routing/trajet.yml"
    prefix:   /trajets

web_service_typecovoit:
    resource: "@WebServiceBundle/Resources/config/routing/typecovoit.yml"
    prefix:   /typecovoits

web_service_typetrajet:
    resource: "@WebServiceBundle/Resources/config/routing/typetrajet.yml"
    prefix:   /typetrajets

web_service_typevehicule:
    resource: "@WebServiceBundle/Resources/config/routing/typevehicule.yml"
    prefix:   /typevehicules

web_service_utilisateur:
    resource: "@WebServiceBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateurs

web_service_ville:
    resource: "@WebServiceBundle/Resources/config/routing/ville.yml"
    prefix:   /villes

web_service_voiture:
    resource: "@WebServiceBundle/Resources/config/routing/voiture.yml"
    prefix:   /voitures

