web_service_homepage:
    path: /
    defaults: { _controller: WebServiceBundle:Default:index }

web_service_get_trajet:
    path: /trajet/{id}/info
    defaults: { _controller: WebServiceBundle:Trajet:getTrajet }
    methods: GET
    requirements:
        id: '\d+'

web_service_get_trajets:
    path: /trajets
    defaults: { _controller: WebServiceBundle:Trajet:getTrajets }
    methods: GET

web_service_get_trajets_utilisateur:
    path: /utilisateur/{id}/trajets
    defaults: { _controller: WebServiceBundle:Covoiturage:getTrajetsUtilisateur }
    methods: GET
    requirements:
        id: '\d+'

web_service_register_to_a_trajet:
    path: /trajet/{id_trajet}/utilisateur/{id_user}
    defaults: { _controller: WebServiceBundle:Covoiturage:registerToATrajet }
    methods: POST
    requirements:
        id_user: '\d+'
        id_trajet: '\d+'

web_service_get_utilisateur:
    path: /utilisateur/{id}/info
    defaults: { _controller: WebServiceBundle:Utilisateur:getUtilisateur }
    methods: GET
    requirements:
        id: '\d+'

web_service_create_utilisateur:
    path: /utilisateur/create
    defaults: { _controller: WebServiceBundle:Utilisateur:createUtilisateur }
    methods: POST

web_service_delete_utilisateur:
    path: /utilisateur/{id}/delete
    defaults: { _controller: WebServiceBundle:Utilisateur:deleteUtilisateur }
    methods: DELETE
    requirements:
        id: '\d+'

web_service_get_possede:
    path: /possede/{id}
    defaults: { _controller: WebServiceBundle:Possede:getPossede }
    methods: GET
    requirements:
        id: '\d+'

web_service_create_possede:
    path: /possede/create
    defaults: { _controller: WebServiceBundle:Possede:createPossede }
    methods: POST

web_service_delete_possede:
    path: /possede/{id}/delete
    defaults: { _controller: WebServiceBundle:Possede:deletePossede }
    methods: DELETE
    requirements:
        id_user: '\d+'
        id_voiture: '\d+'