api_covoiturage_utilisateur_list:
    path: /utilisateurs/{id}
    defaults: { _controller: WebServiceBundle:Covoiturage:getCovoituragesOfUtilisateur }
    methods: GET
    requirements:
        id: '\d+'

api_covoiturage_trajet_list:
    path: /trajets/{id}
    defaults: { _controller: WebServiceBundle:Covoiturage:getCovoituragesOfTrajet }
    methods: GET
    requirements:
        id: '\d+'

api_register_to_a_trajet:
    path: /trajets/{id_trajet}/utilisateurs/{id_user}
    defaults: { _controller: WebServiceBundle:Covoiturage:registerToATrajet }
    methods: POST
    requirements:
        id_user: '\d+'
        id_trajet: '\d+'
