api_possede_utilisateur_list:
    path: /utilisateur/{id}
    defaults: { _controller: WebServiceBundle:Possede:getPossedesUtilisateur }
    methods: GET
    requirements:
        id: '\d+'

api_possede_show:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Possede:getPossede }
    methods: GET
    requirements:
        id: '\d+'

api_possede_new:
    path: /
    defaults: { _controller: WebServiceBundle:Possede:newPossede }
    methods: POST

api_possede_edit:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Possede:editPossede }
    methods: POST
    requirements:
        id: '\d+'

api_possede_delete:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Possede:deletePossede }
    methods: DELETE
    requirements:
        id_user: '\d+'
        id_voiture: '\d+'