api_trajet_list:
    path: /
    defaults: { _controller: WebServiceBundle:Trajet:getTrajets }
    methods: GET

api_trajet_show:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Trajet:getTrajet }
    methods: GET
    requirements:
        id: '\d+'

api_trajet_new:
    path: /utilisateurs/{id}
    defaults: { _controller: WebServiceBundle:Trajet:newTrajet }
    methods: POST
    requirements:
        id: '\d+'

api_trajet_edit:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Trajet:editTrajet }
    methods: POST
    requirements:
        id: '\d+'

api_trajet_delete:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Trajet:deleteTrajet }
    methods: DELETE
    requirements:
        id: '\d+'