api_utilisateur_show:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Utilisateur:getUtilisateur }
    methods: GET
    requirements:
        id: '\d+'

api_utilisateur_new:
    path: /
    defaults: { _controller: WebServiceBundle:Utilisateur:newUtilisateur }
    methods: POST

api_utilisateur_edit:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Utilisateur:editUtilisateur }
    methods: POST
    requirements:
        id: '\d+'

api_utilisateur_delete:
    path: /{id}
    defaults: { _controller: WebServiceBundle:Utilisateur:deleteUtilisateur }
    methods: DELETE
    requirements:
        id: '\d+'