covoiturage_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Covoiturage:index" }
    methods:  GET

covoiturage_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:Covoiturage:show" }
    methods:  GET

covoiturage_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Covoiturage:new" }
    methods:  [GET, POST]

covoiturage_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:Covoiturage:edit" }
    methods:  [GET, POST]

covoiturage_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:Covoiturage:delete" }
    methods:  DELETE
