# Routes liées aux possession de voitures

possede_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Possede:index" }
    methods:  GET

possede_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:Possede:show" }
    methods:  GET

possede_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Possede:new" }
    methods:  [GET, POST]

possede_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:Possede:edit" }
    methods:  [GET, POST]

possede_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:Possede:delete" }
    methods:  DELETE
