<?php

namespace BackOfficeBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository {

    public function getCategories() {
        $em = $this->createQueryBuilder("c")
            ->getQuery();
        
        return $em->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
    
}