<?php

namespace BackOfficeBundle\Repository;

/**
 * Co2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Co2Repository extends \Doctrine\ORM\EntityRepository {
    
}
