<?php

namespace BackOfficeBundle\Repository;

use BackOfficeBundle\Entity\Utilisateur;

/**
 * PossedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossedeRepository extends \Doctrine\ORM\EntityRepository {

    public function getVoitureUtilisateur($id) {
        $em = $this->createQueryBuilder("p")
            ->innerJoin("p.utilisateur", "u")
            ->where("u.id = :id")
            ->setParameter("id", $id)
            ->getQuery();
        
        return $em->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }

    public function deleteVoitureUtilisateur($id) {
        $em = $this->createQueryBuilder("p")
            //->delete()
            ->where("p.id = :id")
            ->setParameter("id", $id)
            ->getQuery();
        
        return $em->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
    
}
