<?php

namespace BackOfficeBundle\Repository;

use BackOfficeBundle\Entity\Utilisateur;

/**
 * PossedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossedeRepository extends \Doctrine\ORM\EntityRepository {

    public function getPossede($id, $hydrated = false) {
        $em = $this->createQueryBuilder("p")
            ->select(["p", "u"])
            ->innerJoin("p.utilisateur", "u")
            ->where("u.id = :id")
            ->setParameter("id", $id)
            ->getQuery();

        if($hydrated)
            return $em->getArrayResult();

        return $em->getResult();
    }

    public function deletePossede($id, $hydrated = false) {
        $em = $this->createQueryBuilder("p")
            ->delete()
            ->where("p.id = :id")
            ->setParameter("id", $id)
            ->getQuery();
        
        if($hydrated)
            return $em->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        
        return $em->getOneOrNullResult();
    }
    
}
