<?php

namespace BackOfficeBundle\Repository;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends \Doctrine\ORM\EntityRepository {
    public function getLastTrajets($nbOfTrajets) {
        if($nbOfTrajets < 1)
            return null;

        $query = $this->createQueryBuilder("t")
            ->orderBy("t.id", "DESC")
            ->setMaxResults($nbOfTrajets)
            ->getQuery();

        return $query->getResult();
    }
}
