<?php

namespace BackOfficeBundle\Repository;

/**
 * TypeTrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVehiculeRepository extends \Doctrine\ORM\EntityRepository {

    public function getTypeVehicules($hydrated = false) {
        $em = $this->createQueryBuilder("tv")
            ->getQuery();
        
        if($hydrated)
            return $em->getArrayResult();

        return $em->getResult();
    }
    
}