<?php

namespace BackOfficeBundle\Repository;

/**
 * TypeCovoitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCovoitRepository extends \Doctrine\ORM\EntityRepository {

    public function getTypeCovoits($hydrated = false) {
        $em = $this->createQueryBuilder("tc")
            ->getQuery();
        
        if($hydrated)
            return $em->getArrayResult();

        return $em->getResult();
    }
    
}