<?php

namespace BackOfficeBundle\Repository;

/**
 * TypeCovoitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCovoitRepository extends \Doctrine\ORM\EntityRepository {

    public function getTypesCovoit() {
        $em = $this->createQueryBuilder("tc")
            ->getQuery();
        
        return $em->getArrayResult();
    }
    
}