<?php

namespace BackOfficeBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository {
    public function getLastUtilisateurs($nbOfUtilisateurs) {
        if($nbOfUtilisateurs < 1)
            return null;

        $em = $this->createQueryBuilder("u")
            ->orderBy("u.id", "DESC")
            ->setMaxResults($nbOfUtilisateurs)
            ->getQuery();

        return $em->getResult();
    }

    public function countUtilisateurs() {
        $em = $this->createQueryBuilder("u")
            ->select("COUNT(u.id)")
            ->getQuery();
        
        return $em->getSingleScalarResult();
    }

    public function getUtilisateur($id) {
        $em = $this->createQueryBuilder("u")
            ->where("u.id = :id")
            ->setParameter("id", $id)
            ->getQuery();
        
        return $em->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
    
}
