<?php

namespace BackOfficeBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository {

    public function getVilles() {
        $em = $this->createQueryBuilder("v")
            ->getQuery();
        
        return $em->getArrayResult();
    }
    
}