<?php

namespace BackOfficeBundle\Repository;

/**
 * PossedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends \Doctrine\ORM\EntityRepository {

    public function getVoitures() {
        $em = $this->createQueryBuilder("v")
            ->getQuery();
        
        return $em->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
    
}